edc_describe/urls.py
from django.conf.urls import url, patterns

from .views import model_data_inspector_view, model_instance_counter

urlpatterns = patterns('',
    url(r'^(?P<app_label>\w+)/(?P<model_name>\w+)/$',
        model_data_inspector_view,
        name="model_data_inspector_url_name"
        ),

    url(r'^(?P<app_label>\w+)/$',
        model_data_inspector_view,
        name="model_data_inspector_url_name"
        ),

    url(r'^counter/',
        model_instance_counter,
        name="model_instance_counter_url_name"
        ),

    url(r'',
        model_data_inspector_view,
        name="model_data_inspector_url_name"
        ),
    )

edc_describe/models/related.py
from django.db import models

from edc_base.model.models import BaseUuidModel


class Related (BaseUuidModel):

    """A model to refer to when the 'option' or 'choice' field name (related_to_field_name) of the foreignkey is not obvious, e.g. not = 'name'.  """

    app_label = models.CharField(
        max_length=50,
        db_index=True)

    model_name = models.CharField(
        max_length=50,
        db_index=True)

    field_name = models.CharField(
        max_length=50,
        db_index=True)

    related_to_model = models.CharField(
        max_length=50)

    related_to_field_name = models.CharField(
        max_length=50)

    objects = models.Manager()

    def __unicode__(self):
        return '%s__%s' % (self.model_name, self.field_name)

    class Meta:
        app_label = "model_describer"
        db_table = "bhp_describer_related"
        unique_together = ['app_label', 'model_name', 'field_name']

edc_describe/forms/model_instance_counter_form.py
from django import forms


class ModelInstanceCounterForm(forms.Form):

    producer = forms.CharField(
        max_length=50,
        label="Producer",
        initial='',
        required=False,
        help_text='This is the name of the producer / hostname , e.g. mpp50, mkl71, etc')

    app_label = forms.CharField(
        max_length=50,
        label="App Label",
        initial='',
        required=False,
        help_text='All or part of the app_label. E.g maikalelo_, mpepu_, mochudi_,  etc')

    key_field = forms.CharField(
        max_length=50,
        label="Key Field",
        initial='id',
        required=False,
        help_text='If your not sure just use "id"')

edc_describe/views/model_data_inspector_view.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext

from edc.dashboard.section.classes import site_sections

from ..classes import ModelSelector
from ..forms import ModelSelectorForm

from ..classes import ModelDataInspector


@login_required
def model_data_inspector_view(request, **kwargs):

    section_name = 'reports'
    template = 'model_data_inspector.html'
    app_label = kwargs.get('app_label')
    model_name = kwargs.get('model_name')
    report_title = ''
    form = ModelSelectorForm()
    context = {
        'sections': site_sections.get_indexed_section_tuples(),
        'form': form,
        'table': '',
        'section_name': section_name,
        'selected_section': section_name,
        'report_title': report_title,
        'report': '',
        'report_name': kwargs.get('report_name'),
        }

    if request.method == 'POST' or (app_label and model_name):
        form = ModelSelectorForm(request.POST or {'app_label': app_label, 'model_name': model_name})
        if form.is_valid():
            app_label = form.cleaned_data.get('app_label') or app_label
            model_name = form.cleaned_data.get('model_name') or model_name
            model_selector = ModelSelector(app_label, model_name)
            model_data_inspector = ModelDataInspector(app_label, model_name)
            if model_data_inspector.get_model():
                summary = model_data_inspector.summarize()
                group = model_data_inspector.group()
                group_m2m = model_data_inspector.group_m2m()
                context = {
                    'sections': site_sections.get_indexed_section_tuples(),
                    'selected_section': section_name,
                    'form': form,
                    'app_label': model_selector.get_app_label(),
                    'model_name': model_selector.get_model_name(),
                    'app_labels': model_selector.get_app_labels(),
                    'model_names': model_selector.get_model_names(),
                    'summary_fields': summary['fields'],
                    'group_fields': group['fields'],
                    'group_m2m_fields': group_m2m['fields'],
                    'fields': model_data_inspector.get_model()._meta.fields,
                    'section_name': section_name,
                    'report_title': model_selector.get_model()._meta.verbose_name,
                    'cumulative_frequency': 0,
                    }
    else:
        form = ModelSelectorForm()
        model_selector = None
    return render_to_response(template, context, context_instance=RequestContext(request))

edc_describe/views/model_group_describer.py
from django.conf import settings

from .base_model_group_describer import base_model_group_describer


def model_group_describer(request, **kwargs):

    if not 'APP_NAME' in dir(settings):
        raise KeyError('Cannot find key \'APP_NAME\' in settings file. e.g APP_NAME=\'maikalelo\'')
    if not 'SUBJECT_APP_LIST' in dir(settings):
        raise KeyError('Cannot find key \'SUBJECT_APP_LIST\' in settings file. e.g SUBJECT_APP_LIST=[\'maikalelo_maternal\',]')
    return base_model_group_describer(request, app_name=settings.APP_NAME, app_list=settings.SUBJECT_APP_LIST, **kwargs)

edc_describe/views/model_instance_counter.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext

from ..classes import ModelInstanceCounter
from ..forms import ModelInstanceCounterForm


@login_required
def model_instance_counter(request, **kwargs):

    section_name = kwargs.get('section_name')
    report_title = 'Model Instance Counts'
    template = 'model_instance_counter.html'

    if request.method == 'POST':

        form = ModelInstanceCounterForm(request.POST)

        if form.is_valid():

            producer = form.cleaned_data['producer']
            app_label = form.cleaned_data['app_label']
            key_field = form.cleaned_data['key_field']

            app_and_field = {'app_label': app_label, 'key_field': key_field}

            counter = ModelInstanceCounter(producer, app_and_field)

            context = {
                'form': form,
                'app_label': app_label,
                'key_field': key_field,
                'producer': producer,
                'result': counter.get(),
                'section_name': section_name,
                'app_name': settings.APP_NAME,
                'report_title': report_title,
                }

        return render_to_response(template, context, context_instance=RequestContext(request))

    else:

        form = ModelInstanceCounterForm(request.GET)
        app_label = request.GET.get('app_label', None)
        key_field = request.GET.get('key_field', None)
        producer = request.GET.get('producer', None)

    return render_to_response(template, {
                'form': form,
                'app_label': app_label,
                'key_field': key_field,
                'producer': producer,
                'result': {},
                'section_name': section_name,
                'app_name': settings.APP_NAME,
                'report_title': report_title,
                }, context_instance=RequestContext(request))

edc_describe/templates/base_model_data_inspector.html
{% extends "section.html"%}
{% load admin_urls %}
{% load url from future %}
{% load describer_tags %}{% load common_tags %}


{% block breadcrumbs %}
    
    <div class="breadcrumbs">
        <a href="/{% app_name %}">Home</a>
        {% if selected_section  %}
            &rsaquo; <a href="{% url 'section_url' section_name=section_name %}">{{ selected_section|capfirst }}</a>
        {% endif %}        
        {% if selected_section  %}
            &rsaquo; <a href="{% url 'model_data_inspector_url_name' %}">Model Data Summary</a>
        {% endif %}        
        {% if report_title  %}
            &rsaquo; {{ report_title }}
        {% endif %}        
        
    </div>
    
{% endblock %}


{% block section_tiles %}

{% if form %}
    {{ form.errors }}
    <div id="search_tile">
    <form class="form" action="" method="post">
        {% csrf_token %}
        {# Include the hidden fields #}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {# Include the visible fields #}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        {% endfor %}<input type="submit" value="Select">
    </form>
    </div>
{% endif %}


{% if app_label and model_name %}

    {% block inspector %} {% endblock %}
    
{% endif %}

{% if list_text_field %}

    {% block list_text_field %}{% endblock %}

{% endif %}
{% endblock %}

edc_describe/templates/describer_form.html
<form action="." method="POST">
<div style='display:none'>  
  {% csrf_token %}
</div>
<table>
<tr>
<td class="field">
    {{ form.app_label.errors }}
    <label for="id_app_label">App_label</label>
    {{ form.app_label }}
</td>
<td class="field">
    {{ form.model_name.errors }}
    <label for="id_model_name">Model Name</label>
    {{ form.model_name }}
</td>
<td>
    <input type="submit" value="Submit" class="default" name="submit" />
</td>

<script type="text/javascript">document.getElementById("id_app_label").focus();</script>
<script type="text/javascript">
    (function($) {
        var field = null;
    })(django.jQuery);
</script>
    </table>
</form>

    

edc_describe/templates/list_apps.html
    <h4>Appications</h4>
    <i>Click on an application below</i>
    <table class="result">
    <tbody>
        {% for app_label in app_labels %}
            <tr class="{% cycle 'row1' 'row2'%}">
            <td><A href="?app_label={{app_label}}">{{app_label}}</A></td>
            </tr>
        {% endfor %}    
    </tbody>
    </table>

edc_describe/templates/list_models.html
    <h4>Model Names for Application {{app_label}}</h4>
    <i>Click on a model below</i>
    <table class="result">
    <tbody>
        {% for model_name in model_names %}
            <tr class="{% cycle 'row1' 'row2'%}">
            <td><A href="?app_label={{app_label}}&model_name={{model_name.module_name}}">{{model_name.verbose_name}}</A></td>
            </tr>
        {% endfor %}    
    </tbody>
    </table>

edc_describe/templates/model_data_inspector.html
{% extends "base_model_data_inspector.html"%}
{% load describer_tags %}{% load common_tags %}

{% block inspector %}

<h3>Model: {{ model_name }}</h3>

{% if summary_fields %}
<h4>Summary Fields</h4>
<table class="result">
<thead>
<th>table</th>
<th>field</th>
<th>freq</th>
<th>sum</th>
<th>avg</th>
<th>min</th>
<th>max</th>
<th>stddev</th>
<th>variance</th>
</thead>
<tbody>
{% for field, aggregates in summary_fields.items %}
    <tr class="{% cycle 'row1' 'row2'%}">
    <td>{{table}}</td>
    <td>{{field}}</td>
   <td>{{ aggregates.count }}</td>
   <td>{{ aggregates.sum }}</td>
   <td>{{ aggregates.avg }}</td>
    <td>{{ aggregates.min }}</td>
   <td>{{ aggregates.max }}</td>
   <td>{{ aggregates.stddev }}</td>
   <td>{{ aggregates.variance }}</td>   
      </tr>
    

{% endfor%}
</tbody>
</table>    

{% endif %}

{% if group_fields %}
<h4>Group Fields</h4>

<table class="result">
<thead>
<th>table</th>
<th>field</th>
<th>label</th>
<th>freq.</th>
<th>cumulative freq.</th>
</thead>
<tbody>
{% for field, aggregates in group_fields.items %}
    {% cycle 'row1' 'row2' as rowcolors silent %}
    {% for aggregate in aggregates %}
        {% update_cumulative_frequency aggregate.count cumulative_frequency forloop.counter as cumulative_frequency %}  
        <tr class="{{ rowcolors }}">
        <td>{{table}}</td>
        <td>{{field}}</td>
        <td>{{ aggregate.label }}</td>
        <td>{{ aggregate.count }}</td>        
        <td>{% if forloop.last %}<B>{% endif %}{{ cumulative_frequency }}{% if forloop.last %}</B>{% endif %}</td>
        </tr>
    {% endfor%}

{% endfor%}
</tbody>
</table>
{% endif %}
{% if group_m2m_fields %}
<h4>Group Many to Many Fields</h4>

<table class="result">
<thead>
<th>table</th>
<th>field</th>
<th>label</th>
<th>freq.</th>
<th>cumulative freq.</th>
</thead>
<tbody>
{% for field, aggregates in group_m2m_fields.items %}
    {% cycle 'row1' 'row2' as rowcolors silent %}
    {% for aggregate in aggregates %}
        {% if forloop.counter == 1 %}
            {% update_total aggregates as total %}
        {% endif %}
        {% update_cumulative_frequency aggregate.count cumulative_frequency forloop.counter as cumulative_frequency %}
        <tr class="{{ rowcolors }}">
        <td>{{table}}</td>
        <td>{{field}}</td>
        <td>{{ aggregate.label }}</td>
        <td>{{ aggregate.count }}</td> 
        <td>{% if forloop.last %}<B>{% endif %}{{ cumulative_frequency }}{% if forloop.last %}</B>{% endif %}</td>
        <td>{% if forloop.last %}<B>{% endif %}{{ aggregate.count|divide_by:total|floatformat:3 }}{% if forloop.last %}</B>{% endif %}</td>        
        </tr>
    {% endfor%}

{% endfor%}


</tbody>
</table>    
{% endif %}

{% if fields %}
<h4>Model</h4>
<table class="result" width="700px">
<thead>
<th>field</th>
<th>verbose_name</th>
<th>help_text</th>
</thead>
<tbody>

{% for field in fields %}
    <tr class="{% cycle 'row1' 'row2'%}">
    <td><B>{{field.name }}</B></td>
    <td>{{ field.verbose_name }}</td>
    <td>{{ field.help_text }}</td>
    </tr>
{% endfor %}
</tbody>
</table>    
{% endif%}

{% endblock %}

edc_describe/templates/model_group_describer.html
{% extends "section.html"%}
{% load common_tags %}{% load describer_tags %}

{% block content %}

<A name="top"></A>
<form action="." method="POST">
<div style='display:none'>  
  {% csrf_token %}
</div>

<table>
<tr>
{% for f in form %}
<td class="field">
    {{ f.errors }}
    <label for="id_{{f.name}}">{{f.label}}</label>
    {{ f }}
</td>
{% endfor %}
<td>
    <input type="submit" value="Submit" class="default" name="submit" />
</td>

<script type="text/javascript">document.getElementById("id_app_label").focus();</script>
<script type="text/javascript">
    (function($) {
        var field = null;
    })(django.jQuery);
</script>
    </table>
</form>

{% if model_list %}
    <H4>{{ model_list_title }}</H4>

    <OL>
    {%for model in model_list %}
    <LI>{% if model_reports %}<A href="#{{model.module_name}}">{% endif %}{{ model.verbose_name|capfirst }}</A></LI>
    {% endfor %}
    </OL>
{% endif %}

{% if model_reports %}
    <H4>Data Summaries by Site and Gender</H4>
{% endif %}

{% for ordered_key in model_reports_ordered_keys %}
    {% for key, model_report in model_reports.items %}
    {% if key == ordered_key %}
    <P><A name="{{model_report.name}}"></A></P>
    <B>{{ model_report.verbose_name }}</B>&nbsp;[<A href="#top">top</A>]
    <table id=result">
    <thead>
    <th>Month</th>
    {% for site in sites %}    
      <th colspan="1">{{ site }}</th>
    {% endfor %}
    <th>total</th>
    </thead>    
    <tbody>
    {% for year in years %}
        {% for month in months %}
            <tr>        
            <td>{{ year }}-{{ month }}</td>
            {% for site in sites %}    
                {% for data in model_report.data %}
                    {% if forloop.first %}
                        <td align="right">
                    {% endif %}    
                    {% if data.site_name == site and data.month == month %} 
                        {% update_cumulative_frequency data.frequency cumulative_frequency as cumulative_frequency %}                
                        {{ data.frequency }}{{ data.gender }}
                    {% endif %}
                    {% if forloop.last%}
                        {% if not cumulative_frequency == 0 %}={% endif %}
                        {{cumulative_frequency|rjust:"30" }}</td>
                    {% endif %}    
                    
                {% endfor %}
            {% endfor %}    
            {% for month_total in model_report.month_totals %}
                {% if month_total.year == year and month_total.month == month %}
                    <td align="right">{{ month_total.total }}</td>        
                {% endif %}  
            {% endfor %}                  
            </tr>                
        {% endfor %}
        {% for year_total in model_report.year_totals %}
            {% if year_total.year == year %}        
                <tr><td colspan=5>{{ year }}</td><td align="right">{{ year_total.total|rjust:"30" }}</td></tr>         
            {% endif %}                  
        {% endfor %}                    
    {% endfor %}    
    <tr><td colspan=5>TOTAL</td><td align="right">{{ model_report.total|rjust:"30" }}</td></tr>
    <tr><td><small>({{ model_report.date_grouping_field }})</small></td><td colspan=5></td></tr>                              
    </tbody>
    </table>
{% endif %}                      
{% endfor %}        
{% endfor %}    
{% endblock%}

edc_describe/templates/model_instance_counter.html
{% extends "section.html"%}
{% load describer_tags %}{% load common_tags %}

{% block content %}
<form action="." method="POST">
<div style='display:none'>  
  {% csrf_token %}
</div>
<table>
<tr>
{{ form }}
<td>
    <input type="submit" value="Submit" class="default" name="submit" />
</td>

<script type="text/javascript">document.getElementById("id_producer").focus();</script>
<script type="text/javascript">
    (function($) {
        var field = null;
    })(django.jQuery);
</script>
    </table>
</form>


<H4>Counts for Models in App : {{ app_label }}</H4>
<table>
<thead>
<th>Model</th>
<th>Count</th>
</thead>
{% for app_label, count in result.iteritems %}
    <thead><th colspan="2"><B>{{ app_label }}</B></th></thead>
    <tbody>
    {% for r in count %}
    <tr class="{% cycle 'row1' 'row2' %}"><td><A href="/admin/{{ app_label }}/{{ r.1 }}/?hostname_created={{ producer }}">{{r.0}}</A></td><td>{{r.2}}</td></tr>
    {% endfor %}
{% endfor %}
</tbody>
</table>
{% endblock %}

edc_describe/templates/section_statistics.html
{% extends "section.html"%}

{% block breadcrumbs %}
    {% comment %}
        named urls. see urls.py 
        use the name and pass the url parameter to 
        successfully reverse 
    {%endcomment %}
    {% url 'statistics_url_name' section_name as section %}
    {% url 'report_url_name section_name' report_name as url_report_url_name %}
    {% url 'section_search_url_name' section_name search_name search_by_name as section_search_by_name %}    

    <div class="breadcrumbs">
        <a href="/{{app_name}}">Home</a>
        {% if section_name  %}
            &rsaquo; <a href="/{{app_name}}/{{ section_name}}/">{{ section_name|capfirst }}</a>
        {% endif %}        
        {% if report_name %}
            &rsaquo; <a  href="{{ url_report_url_name }}">{{ report_name|capfirst }}</a>    
        {% endif %}  
        {% if report_title %}
            &rsaquo; {{ report_title|capfirst }}</a>    
        {% endif %}  
        {% if app_label and not model_name %}
            &rsaquo; {{ app_label|capfirst }}</a>    
        {% endif %}  
        {% if app_label and model_name %}
            &rsaquo; {{ app_label|capfirst }} &rsaquo; {{ model_name|capfirst }}</a>    
        {% endif %}  
        
    </div>
    
{% endblock %}
{% block section_title%}{% endblock%}

{% block section_links%}
<H3>Reports</H3>
<ul class="list_of_reports">
<LI><A href="model_describer/">Model Description and Data Summary</A>
<LI>Model Summaries by Site and Gender
    <UL>
    <LI><A href="model_describer/registered_subject/">Registration and Study Status Models</A>
    {% for fld in visit_fields %}
        <LI><A href="model_describer/{{ fld }}/">Scheduled {{ fld }} models</A>
    {% endfor %}
    <LI><A href="model_describer/counter/">Model Instance Counter</A>
    </ul></LI>
</ul>
{% endblock%}

{% block report %}{% endblock report%}

edc_describe/templates/selector_buttons.html
<table>
    <tr>
    <td class="field">
    <form action="{% url 'model_data_inspector_url_name' %}" method="POST">
    <div style='display:none'>{% csrf_token %}</div>
    <input type="submit" value="List applications" class="default" name="a" />
    </form>
    </td>
    {% if app_label %}
        <td class="field">
        <form action="{% url 'model_data_inspector_url_name' app_label=app_label %}" method="POST">
        <div style='display:none'>{% csrf_token %}</div>
        <input type="submit" value="List models for {{app_label}}" class="default" name="m" /></td>    
        </form>    
    {% endif %}
    </tr></table>

edc_describe/templates/selector_form.html
<form action="." method="POST">
<div style='display:none'>  
  {% csrf_token %}
</div>
<table>
<tr>
<td class="field">
    {{ form.app_label.errors }}
    <label for="id_app_label">App_label</label>
    {{ form.app_label }}
</td>
<td class="field">
    {{ form.model_name.errors }}
    <label for="id_model_name">Model Name</label>
    {{ form.model_name }}
</td>
<td>
    <input type="submit" value="Submit" class="default" name="submit" />
</td>

<script type="text/javascript">document.getElementById("id_app_label").focus();</script>
<script type="text/javascript">
    (function($) {
        var field = null;
    })(django.jQuery);
</script>
    </table>
</form>